name: Build Docker

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  docker:
    outputs:
      imageTag: ${{ steps.meta.outputs.json }}
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v3.1.0
        name: Checkout current repository
      - uses: actions/checkout@v3.1.0
        name: Checkout protobuf
        with:
          repository: Uspacy/protobuf
          ref: 'v0.3'
          path: 'protobuf'
          token: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Protobuf
        run: |
             cd protobuf
             make build-go
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          CI_COMMIT_SHA: ${{ steps.date.outputs.date }}
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
